In [2]:
import torch

x = torch.FloatTensor(
    [[1, 2],
    [3, 4]]
).requires_grad_(True)

requires_grad_(True): 이 텐서에 대해 미분값 구하겠다 (기울기 추적용)

In [3]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [4]:
y.backward()

In [5]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


y = sum((x + 2)(x - 2)) = sum(x^2 -4)

delta(-4)/delta(x) = 0

$
\frac{\partial}{\partial x_i}(x_i^2) = 2x_i
$  
따라서 x.grad는 2x

In [6]:
print(x)    # 텐서값 변경 없음. 역전파는 기울기 계산만 하고 수정 안 함

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [8]:
x3.numpy()  # numpy는 autograd 상태 모르기 때문에 바로 numpy로 변환 안 됨

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [9]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

In [10]:
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]])


In [11]:
x2

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)