1. 행렬 곱셈

In [1]:
import torch

x = torch.FloatTensor(
    [[1, 2], [3, 4], [5, 6]]
)
y = torch.FloatTensor(
    [[1, 2], [3, 4]]
)
print(x.shape, y.shape)

torch.Size([3, 2]) torch.Size([2, 2])


In [2]:
z = torch.matmul(x, y)
z.shape

torch.Size([3, 2])

In [3]:
z = x @ y
x.shape

torch.Size([3, 2])

In [5]:
x = torch.FloatTensor(
    [[[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]]]
)
y = torch.FloatTensor(
    [[[1, 2, 2], [1, 2, 2]], [[1, 3, 3], [1, 3, 3]], [[1, 4, 4], [1, 4, 4]]]
)
print(x.shape, y.shape)

torch.Size([3, 3, 2]) torch.Size([3, 2, 3])


In [8]:
z = x @ y
z.shape

torch.Size([3, 3, 3])

In [10]:
x = torch.randn(2, 3, 2)
W = torch.randn(2, 4, 2)
y = x @ W.transpose(1, 2)
y.shape

torch.Size([2, 3, 4])

In [11]:
import torch
import torch.nn as nn

X = torch.FloatTensor([[1.0, 2.0, 3.0]])
W = torch.FloatTensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])

print(X.shape, W.shape)

torch.Size([1, 3]) torch.Size([2, 3])


In [12]:
linear = nn.Linear(
    in_features=3,
    out_features=2,
    bias=False
)

In [13]:
with torch.no_grad():
    linear.weight.copy_(W)

In [14]:
y2 = linear(X)
y2

tensor([[1.4000, 3.2000]], grad_fn=<MmBackward0>)

In [16]:
import numpy as np
def identify_function(x):
    return x
x = np.array([1.0, 2.0, 3.0])
print(identify_function(x))

[1. 2. 3.]


In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([0.0, 2.0, -1.0])
print(sigmoid(x))

[0.5        0.88079708 0.26894142]


In [18]:
def stable_softmax(x):
    x_max = np.max(x)
    exp_x = np.exp(x - x_max)  # 최대값을 빼서 안정적으로 변환
    return exp_x / np.sum(exp_x)

x = np.array([1000, 1001, 1002])  # 큰 값에서도 안정적으로 동작
print(stable_softmax(x))

[0.09003057 0.24472847 0.66524096]
