In [1]:
import torch

In [9]:
a = torch.IntTensor(
    [[1, 2],
    [3, 4]]
)
b = torch.IntTensor(
    [[1, 2],
    [1, 2]]
)

c = torch.matmul(a, b)
c

tensor([[ 3,  6],
        [ 7, 14]], dtype=torch.int32)

1D X 1D => np.dot  
2D X 2D => matrix mul  
고차원 => 행렬 배치 곱

In [10]:
d = a@b
d

tensor([[ 3,  6],
        [ 7, 14]], dtype=torch.int32)

IntTensor도 가능한데 딥러닝 연산은 거의 실수 기반  
따라서 FloatTensor 기본 사용

In [12]:
b = torch.LongTensor(
    [[1, 2],
    [3, 4]]
)

In [13]:
c = torch.ByteTensor(
    [[1, 2],
     [2, 4]]
)

In [14]:
mask = torch.BoolTensor([True, False, True])
mask

tensor([ True, False,  True])

In [21]:
x = torch.FloatTensor(3, 2) 
x

tensor([[3.2509e+01, 2.0753e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [22]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
c = torch.randn(3, 2)
c

tensor([[-0.2764, -0.4826],
        [ 1.3727,  0.1657],
        [ 1.0440, -0.3083]])

In [26]:
import numpy as np
x = np.array(
    [[1, 2],
     [3, 4]]
)
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [27]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [38]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [39]:
x = torch.from_numpy(x)

x.int()

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [40]:
print(x, type(x), x.dtype)

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'> torch.int64


In [43]:
x = x.float()
print(x, type(x), x.dtype)

tensor([[1., 2.],
        [3., 4.]]) <class 'torch.Tensor'> torch.float32


In [45]:
torch.FloatTensor([1, 0, 2]).bool()

tensor([ True, False,  True])

In [46]:
x = torch.FloatTensor(
    [[[1, 2],
      [3, 4]],
      [[5, 6],
       [7, 8]],
       [[9, 10],
       [11, 12]]]
)

In [47]:
x.shape

torch.Size([3, 2, 2])

In [49]:
x.dim()

3

In [50]:
print((len(x.size())))

3


In [ ]:
print(x.size(1))    # PyTorch method
print(x.shape[1])   # Numpy style

2
2


In [53]:
print(x.size(-1))    # PyTorch method
print(x.shape[-1])   # Numpy style

2
2


In [54]:
import torch

a = torch.FloatTensor(
    [[1, 2],
    [3, 4]]
)
b = torch.FloatTensor(
    [[1, 2],
    [1, 2]]
)

a + b

tensor([[2., 4.],
        [4., 6.]])

In [55]:
a - b

tensor([[0., 0.],
        [2., 2.]])

In [56]:
a * b

tensor([[1., 4.],
        [3., 8.]])

In [57]:
a / b

tensor([[1., 1.],
        [3., 2.]])

In [58]:
a == b

tensor([[ True,  True],
        [False, False]])

In [60]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [62]:
print(a.mul(b))

tensor([[1., 4.],
        [3., 8.]])


In [64]:
print(a.mul_(b))    # _ 붙으면 원본 바꾸는 inplace 연산
a

tensor([[ 1.,  8.],
        [ 3., 16.]])


tensor([[ 1.,  8.],
        [ 3., 16.]])

In [65]:
print(a.sum())
print(a.mean())

tensor(28.)
tensor(7.)


In [66]:
print(a.sum(dim=0))
print(a.sum(dim=1))

tensor([ 4., 24.])
tensor([ 9., 19.])


Broadcast: 텐서 차원 다를 때 자동으로 맞춰서 수행

In [68]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.shape, y.shape)

torch.Size([1, 2]) torch.Size([1, 2])


In [71]:
z = x + y
print(z, z.shape)

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [73]:
x = torch.FloatTensor(
    [[1, 2],
    [4, 8]]
)
y = 1

z = x + y
z

tensor([[2., 3.],
        [5., 9.]])

```
1 -> [[1, 1],
      [1, 1]]
```
x와 동일한 shape으로 브로드캐스팅

In [75]:
x = torch.FloatTensor(
    [[1, 2],
    [3, 4]]
)
y = torch.FloatTensor([3, 5])

z = x + y
print(z)

tensor([[4., 7.],
        [6., 9.]])


In [77]:
x = torch.FloatTensor([[[[1, 2]]]])
y = torch.FloatTensor([3, 5])

z = x + y
z

tensor([[[[4., 7.]]]])

In [78]:
x = torch.FloatTensor(
    [[1, 2],
    [3, 4]]
)
y = torch.FloatTensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
z = x + y
z

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [81]:
x = torch.FloatTensor(
    [[[1, 2],
    [3, 4]],
    [[5, 6],
    [7, 8]],
    [[9, 10],
    [11, 12]]]
)
print(x.reshape(12))
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [84]:
x.view(2, 2, 3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

view: 연속된 메모리 구조일 때 사용  
reshape: 필요 시 데이터 복사도 가능한 유연한 재구성 함수

In [87]:
x = torch.FloatTensor(
    [[[1, 2],
    [3, 4]]]
)
print(x.shape)
print(x.squeeze(), x.squeeze().shape)
print(x.squeeze(1), x.squeeze(1).shape)

torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])
tensor([[[1., 2.],
         [3., 4.]]]) torch.Size([1, 2, 2])


squeeze: 특정 차원 1이면 제거  
unsqueeze: 특정 차원 추가

In [92]:
x = torch.FloatTensor(
    [[[1, 2],
    [3, 4]]]
)
print(x.unsqueeze(2), x.unsqueeze(2).shape)
print(x.unsqueeze(-1), x.unsqueeze(-1).shape)

tensor([[[[1., 2.]],

         [[3., 4.]]]]) torch.Size([1, 2, 1, 2])
tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]]]]) torch.Size([1, 2, 2, 1])


In [93]:
x = torch.FloatTensor(
    [[[1, 2],
    [3, 4]],
    [[5, 6],
    [7, 8]],
    [[9, 10],
    [11, 12]]]
)

x.size()

torch.Size([3, 2, 2])

In [94]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [96]:
print(x[0, :, :2])

tensor([[1., 2.],
        [3., 4.]])


In [97]:
print(x[-1])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [98]:

print(x[:, 0, :])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [99]:
print(x[1:3, :, :])

tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [101]:
x = torch.FloatTensor(10, 4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
splits = x.split(4, dim=0)
print(splits)
print(type(splits))

(tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]]))
<class 'tuple'>


In [107]:
for split in splits:
    print(split.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [111]:
x = torch.ones(8, 4)
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


Tensor.split(n, dim): Tensor를 dim 기준 n개씩 자르기  
Tensor.chunk(n, dim): Tensor를 dim 기준 n개로 자르기  

In [112]:
x = torch.FloatTensor(
    [[[1, 2],
    [3, 4]],
    [[5, 6],
    [7, 8]],
    [[9, 10],
    [11, 12]]]
)

indice = torch.LongTensor([2, 1])
x.size()

torch.Size([3, 2, 2])

In [114]:
y = x.index_select(dim=0, index=indice) # dim 차원 indice에서 지정 순서대로 선택
print(y, y.size())

tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]]) torch.Size([2, 2, 2])


index_select 함수는 반환값 있어 텐서 새로 생성됨  
index는 LongTensor 형태로 전달

In [115]:
x.index_select(0, index=torch.LongTensor([0, 0]))

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

In [117]:
x = torch.FloatTensor(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
y = torch.FloatTensor(
    [[10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]]
)

print(x.size(), y.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [120]:
z = torch.cat((x, y), dim=0)
z

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [121]:
z = torch.cat((x, y), dim=1)
z

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

In [125]:
z = torch.stack([x, y])
print(z, z.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


cat(): 차원 수 동일. 기존 축에 이어 풉임  
stack(): 차원 수 + 1. 새로운 축 만들어 쌓음

In [127]:
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z, z.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


In [130]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]
result = torch.stack(result)
print(result, result.shape)

tensor([[[3.2260e+01, 2.0753e-42],
         [2.3694e-38, 0.0000e+00]],

        [[2.3694e-38, 4.4766e+00],
         [3.0000e+00, 4.0000e+00]],

        [[2.3694e-38, 1.1870e-05],
         [3.0000e+00, 4.0000e+00]],

        [[3.2259e+01, 2.0753e-42],
         [2.3694e-38, 2.3694e-38]],

        [[0.0000e+00, 0.0000e+00],
         [2.3694e-38, 2.3694e-38]]]) torch.Size([5, 2, 2])


# PyTorch 메소드

In [148]:
# expand(): 크기 1인 차원을 지정된만큼 확장. 같은 값 반복되는 것처럼 보여줌
# expand는 값 복사가 아닌 같은 메모리 반복 참조
# - 메모리 효율성 좋음
x = torch.FloatTensor(
    [[[1, 2]],
    [[3, 4]]]
)
x.shape

torch.Size([2, 1, 2])

In [149]:
y = x.expand(*[2, 3, 2])
(y, y.shape)

(tensor([[[1., 2.],
          [1., 2.],
          [1., 2.]],
 
         [[3., 4.],
          [3., 4.],
          [3., 4.]]]),
 torch.Size([2, 3, 2]))

In [151]:
y = torch.cat([x, x, x], dim=1)

print(y, y.shape
    )

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


In [152]:
x = torch.randperm(10) # 랜덤 순열
print(x,x.shape)

tensor([9, 7, 6, 3, 5, 8, 2, 0, 4, 1]) torch.Size([10])


In [153]:
x = torch.randperm(3**3).reshape(3, 3, -1)
print(x, x.shape)

tensor([[[21, 15, 18],
         [19, 17,  9],
         [14, 11,  2]],

        [[22, 10, 26],
         [16,  6,  8],
         [13, 20, 25]],

        [[23,  0,  3],
         [ 1,  5, 24],
         [ 7, 12,  4]]]) torch.Size([3, 3, 3])


In [154]:
# argmax(): 최대값 인덱스 반환

In [156]:
k = 1
values, indices = torch.sort(x, dim=1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[21, 19, 14],
        [22, 16, 13],
        [23,  7,  1]])
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 2, 1]])


In [157]:
# masked_fill(): 마스크 True인 위치에 지정 값 채움
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)
print(x, x.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.Size([3, 3])


In [158]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [161]:
y = x.masked_fill(mask, value=-1)
y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

사용처
- 이미지 처리 padding 처리
- loss 계산에서 해당 값 무시

In [162]:
print(x.shape, y.shape)
print(torch.ones_like(x))
print(torch.zeros_like(y))

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
