In [1]:
import numpy as np
print(np.__version__)

2.5.1


In [ ]:
import numpy as np
c = np.array([1, 2, 3])
print(c)

[1 2 3]


In [ ]:
b = np.array([4, 5, 6])
c = c + b
print(c)

[5 7 9]


In [ ]:
print(c.shape)
print(c.size)

(3,)
3


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [6]:
arr = np.zeros((2, 3))  # 2x3 배열
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr = np.ones((3, 2))  # 3x2 배열
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
arr = np.arange(0, 10, 2)  # 0부터 9까지 2씩 증가하는 값
print(arr)

[0 2 4 6 8]


In [9]:
arr = np.linspace(0, 1, 5)  # 0에서 1까지 5개의 등간격 값
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
arr = np.random.randn(2, 3)  # 2x3 배열
print(arr)

[[ 1.68740411 -0.51018031  0.64202373]
 [ 1.28775378  0.18546345  0.04916122]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [12]:
print(arr.ndim)

2


In [13]:
print(arr.size)

6


In [14]:
print(arr.dtype)

int64


In [15]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])

10
30


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])
print(arr[2, 2])

2
9


In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2])

9


In [18]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:, :2])

[[4 5]
 [7 8]]


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[:, 1, :2])

[[ 4  5]
 [10 11]]


In [21]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])

[3 5 7]


In [23]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])

[3 5 7]


In [25]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30])

[40 50]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[arr > 4])

[5 6 7 8 9]


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

[5 7 9]


In [28]:
print(arr1 - arr2)

[-3 -3 -3]


In [29]:
print(arr1 * arr2)

[ 4 10 18]


In [30]:
print(arr1 / arr2)

[0.25 0.4  0.5 ]


In [31]:
print(arr1 ** 2)

[1 4 9]


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

32


In [33]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))

[17 39]


In [34]:
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr2d_1, arr2d_2))

[[19 22]
 [43 50]]


In [35]:
arr = np.array([1, 2, 3])
print(arr + 10)

[11 12 13]


In [36]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([1, 2, 3])
print(arr2d + arr1d)

[[2 4 6]
 [5 7 9]]


In [37]:
arr3d = np.random.rand(3, 1, 4)  # 3x1x4 배열
arr2d = np.random.rand(4, 4)     # 4x4 배열

# 브로드캐스팅을 통해 3차원 배열과 2차원 배열 간 연산 수행
result = arr3d + arr2d
print(result.shape)

(3, 4, 4)


In [38]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
col = np.array([[10], [20]])
print(arr2d.shape, row.shape, col.shape)

(2, 3) (3,) (2, 1)


In [39]:
arr = np.array([10, 20, 30])
print(arr > 15)

[False  True  True]


In [40]:
print(arr == 20)
print(arr != 20)

[False  True False]
[ True False  True]


In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)

[False False  True]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())

15


In [43]:
print(arr.max())
print(arr.min())

5
1


In [44]:
print(arr.std())
print(arr.var())

1.4142135623730951
2.0


In [45]:
print(arr.cumsum())

[ 1  3  6 10 15]


In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.sum(axis=0))
print(arr2d.sum(axis=1))

[5 7 9]
[ 6 15]


In [47]:
arr = np.array([10, 20, 30, 40])
print(np.mean(arr))

25.0


In [48]:
print(np.median(arr))

25.0


In [49]:
from scipy import stats

arr = np.array([10, 20, 20, 30, 40])
print(stats.mode(arr))

ModeResult(mode=np.int64(20), count=np.int64(2))


In [50]:
print(np.var(arr))

104.0


In [51]:
print(np.std(arr))

10.198039027185569


In [52]:
print(np.max(arr) - np.min(arr))

30


In [53]:
import numpy as np
arr = np.array([30, 10, 20, 40, 50])
sorted_arr = np.sort(arr)
print(sorted_arr)

[10 20 30 40 50]


In [54]:
sorted_arr_desc = np.sort(arr)[::-1]
sorted_arr_desc

array([50, 40, 30, 20, 10])

In [55]:
arr2d = np.array([[5, 2, 3], [8, 4, 1]])
sorted_arr2d = np.sort(arr2d)
print(sorted_arr2d)

[[2 3 5]
 [1 4 8]]


In [56]:
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)

[[5 2 1]
 [8 4 3]]


In [57]:
sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)

[[2 3 5]
 [1 4 8]]


In [58]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)

[1 2 0]


In [59]:
arr2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_indices = np.argsort(arr2d, axis=1)
print(sorted_indices)

[[1 2 0]
 [1 2 0]]


In [62]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [63]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [65]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

[[1 2 3]
 [4 5 6]]


In [66]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.hstack((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [67]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [68]:
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)

[[1 4]
 [2 5]
 [3 6]]


In [73]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

con_arr = np.concatenate((arr1, arr2), axis=0)
print(con_arr)
print('--------')
hstacked_arr = np.hstack((arr1, arr2))
print(hstacked_arr)
print('--------')
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)
print('========')
vstacked_arr = np.vstack((arr1, arr2))
print(vstacked_arr)
print('--------')
stacked_arr1 = np.stack((arr1, arr2), axis=1)
print(stacked_arr1)

[1 2 3 4 5 6]
--------
[1 2 3 4 5 6]
--------
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
--------
[[1 4]
 [2 5]
 [3 6]]


In [74]:
import time
size = 1000000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.08376789093017578


In [75]:
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.0026726722717285156


In [76]:
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.1361393928527832


In [77]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.004228353500366211


In [79]:
arr = np.array([1, 2, 3], dtype='int64')
print(arr.nbytes)

24


In [80]:
arr = np.array([1, 2, 3], dtype='int32')
print(arr.nbytes)

12


In [84]:
size = 100000000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

start_time = time.time()
print(sum(list(arr)), time.time() - start_time)

대용량 데이터 합계 성능: 0.10642457008361816
50000830.41673632 9.444362163543701


In [82]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.04222244 0.37174264 0.12350091 0.2316721  0.45527342 0.61023235
 0.04659292 0.72584265 0.87971354 0.59791684]
