In [2]:
import numpy as np
print(np.zeros((4, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
print(np.arange(0, 21, 5))

[ 0  5 10 15 20]


In [5]:
print(np.linspace(0, 1, 4))

[0.         0.33333333 0.66666667 1.        ]


In [6]:
print(np.random.rand(2, 2))

[[0.73865657 0.21846732]
 [0.5910115  0.79546365]]


In [16]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:, 0])
print(arr[1, 2])
print(arr[:2, :2])

[10 40 70]
60
[[10 20]
 [40 50]]


In [20]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(arr[[0, 2, 4]])
print(arr[arr > 50])

[10 30 50]
[60 70 80 90]


In [37]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr > 15) & (arr < 45)]

array([20, 30, 40])

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[arr % 2 == 0])

[2 4 6 8]


In [48]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])
print(sales[sales > 200])
print(sales[sales[:, 2] <= 100, :2])
print(sales[sales[:, 1] >= 150])

[220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.dot(arr2))

32


In [50]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [51]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 20])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())


[30 40 50]
150
50
10
30.0


In [77]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())


150
50
10
30.0


In [79]:
from scipy import stats

arr = np.array([10, 20, 30, 30, 40, 50, 60])
print(np.mean(arr))
print(np.median(arr))
print(stats.mode(arr))
print(np.max(arr) - np.min(arr))


34.285714285714285
30.0
ModeResult(mode=np.int64(30), count=np.int64(2))
50


In [81]:
print(np.random.normal(0, 1, 1000))
print(np.random.uniform(0, 1, 1000))

[-6.87573153e-01  1.24246036e+00  6.43516444e-01 -6.92806399e-01
  2.25910955e+00 -4.13108322e-02 -6.41606580e-01 -1.08261122e+00
  8.12255383e-01 -1.02046217e+00  1.05597335e+00 -1.86760351e+00
 -7.52556050e-01 -1.36354139e+00 -1.64252280e+00  1.29152865e+00
 -2.08859117e-01 -7.56542856e-01 -1.09382609e-01  3.26751044e-01
  2.83848638e-01 -4.65438066e-02 -8.02722087e-01  8.45543488e-02
 -4.90512177e-01 -5.22465930e-01  9.33476010e-01 -1.70779721e+00
 -3.37729016e-01 -1.89648494e-01 -2.50670805e-01  1.25467990e+00
 -5.14437365e-01  3.35331085e-01 -1.75363549e-01  3.00796788e-01
 -7.88146599e-01 -7.98459459e-01  2.66432600e-01 -8.42530354e-01
 -1.25499720e+00  6.61925466e-01  7.24445744e-01  6.80092096e-02
  9.45417321e-01 -6.27611922e-01  1.32504259e-01  2.03058633e+00
 -1.77121561e-01  9.25982108e-01  2.23245675e-02 -1.25454197e-01
 -1.74529851e+00  6.56552942e-01 -1.41695179e+00  1.65354648e-01
 -1.75794041e+00 -1.14553145e+00 -8.72611682e-01 -1.10777630e-01
 -1.15471125e+00 -9.58979

In [90]:
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

print(np.mean([scores_math, scores_english, scores_science], axis=0))
print(np.var([scores_math, scores_english, scores_science], axis=0))
print(np.std([scores_math, scores_english, scores_science], axis=0))

[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
[ 4.22222222  8.22222222  6.22222222  2.66666667  1.55555556  6.
 10.88888889  1.55555556  0.66666667  0.22222222]
[2.05480467 2.86744176 2.49443826 1.63299316 1.24721913 2.44948974
 3.29983165 1.24721913 0.81649658 0.47140452]


In [91]:
arr = np.array([50, 10, 30, 40, 20])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


In [92]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1))

[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]


In [93]:
arr = np.array([15, 10, 20])
arr_arg = np.argsort(arr)
print(np.argsort(arr))
print(arr[arr_arg])

[1 0 2]
[10 15 20]


In [98]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [99]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr1, arr2)))
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.stack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]


In [106]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

sales_info = ['사과', '바나나', '오렌지']

In [107]:
print(np.mean(sales_data, axis=2))

[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


In [145]:
print((np.sum(sales_data, axis=(0))))
print(np.argmax(np.sum(sales_data, axis=0), axis=0))
print(list(sales_info[i] for i in np.argmax(np.sum(sales_data, axis=0), axis=0)))

[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
[0 0 0 0 0 0]
['사과', '사과', '사과', '사과', '사과', '사과']


In [116]:
print(sales_info[np.argmax(np.sum(sales_data, axis=(2, 0)))])

사과


In [159]:
print(sales_data[sales_data > 150])
print(np.where(sales_data > 150))

for bran_i, fru_i, mon_i in zip(*np.where(sales_data > 150)):
    print(f'{mon_i+1}월 {bran_i}지점, 과일: {sales_info[fru_i]}, 판매: {sales_data[bran_i, fru_i, mon_i]}')

[200 230 180 210 170 190 160 180 160 160 180 170 190 160 170 160 180]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 3, 3, 3]), array([0, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0]), array([2, 3, 4, 5, 2, 3, 4, 5, 2, 2, 3, 4, 5, 5, 3, 4, 5]))
3월 0지점, 과일: 사과, 판매: 200
4월 0지점, 과일: 사과, 판매: 230
5월 0지점, 과일: 사과, 판매: 180
6월 0지점, 과일: 사과, 판매: 210
3월 0지점, 과일: 바나나, 판매: 170
4월 0지점, 과일: 바나나, 판매: 190
5월 0지점, 과일: 바나나, 판매: 160
6월 0지점, 과일: 바나나, 판매: 180
3월 0지점, 과일: 오렌지, 판매: 160
3월 2지점, 과일: 사과, 판매: 160
4월 2지점, 과일: 사과, 판매: 180
5월 2지점, 과일: 사과, 판매: 170
6월 2지점, 과일: 사과, 판매: 190
6월 2지점, 과일: 바나나, 판매: 160
4월 3지점, 과일: 사과, 판매: 170
5월 3지점, 과일: 사과, 판매: 160
6월 3지점, 과일: 사과, 판매: 180
