In [7]:
from konlpy.tag import Okt

# 텍스트
text = "자연어 처리는 정말 재미있다!"

# 형태소 분석
okt = Okt()
morphs = okt.morphs(text)
pos = okt.pos(text)

print("형태소 분석 결과:", morphs)
print("품사 태깅 결과:", pos)

형태소 분석 결과: ['자연어', '처리', '는', '정말', '재미있다', '!']
품사 태깅 결과: [('자연어', 'Noun'), ('처리', 'Noun'), ('는', 'Josa'), ('정말', 'Noun'), ('재미있다', 'Adjective'), ('!', 'Punctuation')]


In [9]:
import re

# 원시 텍스트
raw_text = "Hello!!! 자연어 처리 is FUN.   Do you agree? :)"

# 불필요한 기호 제거
clean_text = re.sub(r"[^\w\s]", "", raw_text)

# 소문자 변환
clean_text = clean_text.lower()

# 공백 제거
clean_text = " ".join(clean_text.split())

print("처리된 텍스트:", clean_text)

처리된 텍스트: hello 자연어 처리 is fun do you agree


In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 샘플 데이터
corpus = ["자연어 처리는 재미있다.", "자연어 처리는 어렵다.", "데이터는 유용하다."]

# Bag-of-Words
vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(corpus)
print("Bag-of-Words:\\n", bow.toarray())

# TF-IDF
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus)
print("TF-IDF:\\n", tfidf_matrix.toarray())

Bag-of-Words:\n [[0 0 0 1 1 1]
 [0 1 0 1 0 1]
 [1 0 1 0 0 0]]
TF-IDF:\n [[0.         0.         0.         0.51785612 0.68091856 0.51785612]
 [0.         0.68091856 0.         0.51785612 0.         0.51785612]
 [0.70710678 0.         0.70710678 0.         0.         0.        ]]


In [3]:
# 샘플 텍스트
text = "자연어 처리는 재미있다. 자연어는 어렵지만 재미있다."

# 단어 빈도 계산
from collections import Counter
words = text.split()
word_count = Counter(words)

# 문장 길이 계산
sentences = text.split(". ")
sentence_lengths = [len(sentence.split()) for sentence in sentences]

print("단어 빈도:", word_count)
print("문장 길이:", sentence_lengths)

단어 빈도: Counter({'재미있다.': 2, '자연어': 1, '처리는': 1, '자연어는': 1, '어렵지만': 1})
문장 길이: [3, 3]


In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 임의의 단어 벡터
word1 = np.array([[1, 2, 3]])
word2 = np.array([[2, 3, 4]])

# 코사인 유사도 계산
similarity = cosine_similarity(word1, word2)
print("코사인 유사도:", similarity[0][0])

코사인 유사도: 0.9925833339709303


In [5]:
from konlpy.tag import Okt

# 텍스트 데이터
text = "자연어 처리는 재미있다."

# 형태소 분석
okt = Okt()
morphs = okt.morphs(text)
print("형태소 분석 결과:", morphs)

형태소 분석 결과: ['자연어', '처리', '는', '재미있다', '.']


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("BoW 벡터화 결과:\\n", X.toarray())
print("단어 사전:", vectorizer.vocabulary_)

BoW 벡터화 결과:\n [[0 0 1 1 1]
 [1 1 0 0 0]]
단어 사전: {'자연어': 2, '처리는': 4, '재미있다': 3, 'python으로': 0, '가능하다': 1}


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print("TF-IDF 결과:\\n", X.toarray())
print("단어 사전:", vectorizer.vocabulary_)

TF-IDF 결과:\n [[0.         0.         0.57735027 0.57735027 0.57735027]
 [0.70710678 0.70710678 0.         0.         0.        ]]
단어 사전: {'자연어': 2, '처리는': 4, '재미있다': 3, 'python으로': 0, '가능하다': 1}


In [13]:
from gensim.models import Word2Vec

# 샘플 문장
sentences = [["자연어", "처리", "재미있다"], ["Python", "가능하다"]]

# Word2Vec 모델 학습
model = Word2Vec(sentences, vector_size=100, window=3, min_count=1, sg=0)

# 단어 벡터 확인
print("단어 '자연어'의 벡터:", model.wv["자연어"])

단어 '자연어'의 벡터: [-0.00713902  0.00124103 -0.00717672 -0.00224462  0.0037193   0.00583312
  0.00119818  0.00210273 -0.00411039  0.00722533 -0.00630704  0.00464722
 -0.00821997  0.00203647 -0.00497705 -0.00424769 -0.00310898  0.00565521
  0.0057984  -0.00497465  0.00077333 -0.00849578  0.00780981  0.00925729
 -0.00274233  0.00080022  0.00074665  0.00547788 -0.00860608  0.00058446
  0.00686942  0.00223159  0.00112468 -0.00932216  0.00848237 -0.00626413
 -0.00299237  0.00349379 -0.00077263  0.00141129  0.00178199 -0.0068289
 -0.00972481  0.00904058  0.00619805 -0.00691293  0.00340348  0.00020606
  0.00475375 -0.00711994  0.00402695  0.00434743  0.00995737 -0.00447374
 -0.00138926 -0.00731732 -0.00969783 -0.00908026 -0.00102275 -0.00650329
  0.00484973 -0.00616403  0.00251919  0.00073944 -0.00339215 -0.00097922
  0.00997913  0.00914589 -0.00446183  0.00908303 -0.00564176  0.00593092
 -0.00309722  0.00343175  0.00301723  0.00690046 -0.00237388  0.00877504
  0.00758943 -0.00954765 -0.00800821 -

In [15]:
model.wv.similarity('자연어', '재미있다')

np.float32(0.17018887)

In [17]:
model.wv.most_similar('자연어', topn=5)

[('재미있다', 0.17018885910511017),
 ('Python', 0.004503022879362106),
 ('가능하다', -0.027750348672270775),
 ('처리', -0.04461711645126343)]

In [18]:
import gensim.downloader as api

# 1) 미리 학습된 GloVe 로드 (처음 1번은 다운로드 시간이 걸림)
# 50차원 버전: 가볍고 실습용으로 좋음
glove = api.load("glove-wiki-gigaword-50")

# 2) 단어 벡터 확인 (길이=50)
print("king 벡터 차원:", glove["king"].shape)

# 3) 코사인 유사도
print("similarity(king, queen):", glove.similarity("king", "queen"))
print("similarity(king, banana):", glove.similarity("king", "banana"))

# 4) 가장 비슷한 단어 top-n
print("most_similar('king'):", glove.most_similar("king", topn=5))

# 5) 벡터 연산(관계) 예시: king - man + woman ≈ queen
print(glove.most_similar(positive=["king", "woman"], negative=["man"], topn=5))

[==================================================] 100.0% 66.0/66.0MB downloaded
king 벡터 차원: (50,)
similarity(king, queen): 0.78390425
similarity(king, banana): 0.22074081
most_similar('king'): [('prince', 0.8236179351806641), ('queen', 0.7839043140411377), ('ii', 0.7746230363845825), ('emperor', 0.7736247777938843), ('son', 0.766719400882721)]
[('queen', 0.8523604273796082), ('throne', 0.7664334177970886), ('prince', 0.7592144012451172), ('daughter', 0.7473883628845215), ('elizabeth', 0.7460219860076904)]


In [19]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# 1) 예시 문서(문장) 준비
docs = [
    "자연어 처리는 재미있다",
    "파이썬으로 자연어 처리를 할 수 있다",
    "축구 경기는 정말 재미있다",
    "오늘 날씨가 좋다"
]

# 2) Doc2Vec은 문서마다 태그(아이디)가 필요함
tagged_docs = [
    TaggedDocument(words=d.split(), tags=[f"DOC_{i}"])
    for i, d in enumerate(docs)
]

# 3) Doc2Vec 모델 학습
model = Doc2Vec(
    documents=tagged_docs,
    vector_size=50,   # 문서 벡터 차원
    window=3,         # 문맥 범위
    min_count=1,      # 최소 등장 횟수
    workers=2,        # CPU 쓰레드
    epochs=50         # 학습 반복
)

# 4) 학습된 문서 벡터 확인
print("DOC_0 벡터 일부:", model.dv["DOC_0"][:10])

# 5) 특정 문서와 가장 유사한 문서 찾기
print("\nDOC_0와 유사한 문서:")
print(model.dv.most_similar("DOC_0", topn=3))

# 6) 새 문장(학습에 없던 문장)도 벡터로 추정 가능(infer_vector)
new_doc = "자연어 처리는 파이썬으로 가능하다"
new_vec = model.infer_vector(new_doc.split())

print("\n새 문장과 유사한 문서:")
print(model.dv.most_similar([new_vec], topn=3))

DOC_0 벡터 일부: [-0.01058207 -0.01189603 -0.01985634  0.01694183  0.00701691  0.00072557
 -0.01981407 -0.01017613 -0.01967002  0.00412226]

DOC_0와 유사한 문서:
[('DOC_1', 0.2878270447254181), ('DOC_2', 0.1307842880487442), ('DOC_3', -0.07168306410312653)]

새 문장과 유사한 문서:
[('DOC_2', 0.2660405933856964), ('DOC_1', 0.04592357203364372), ('DOC_3', 0.013086807914078236)]


In [20]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

# LDA 모델 학습
lda = LatentDirichletAllocation(n_components=2, random_state=0)
lda.fit(X)

# 주제별 단어 분포
print("주제별 단어 분포:\\n", lda.components_)

주제별 단어 분포:\n [[1.4913572  1.4913572  0.50945773 0.50945773 0.50945773]
 [0.5086428  0.5086428  1.49054227 1.49054227 1.49054227]]


In [21]:
from gensim.models import FastText   # 서브워드(n-그램) 기반 단어 임베딩 모델 FastText

# 1) 토큰화된 문장(리스트의 리스트) 준비
sentences = [
    ["자연어", "처리", "재미있다"],                          # 문장1 토큰 리스트
    ["파이썬", "으로", "자연어", "처리", "가능하다"],          # 문장2 토큰 리스트
    ["자연어", "처리", "공부", "하자"]                         # 문장3 토큰 리스트
]

# FastText: 단어를 '문자 n-그램(서브워드)' 조합으로도 표현해 OOV(미등장 단어) 벡터 생성에 강함
model = FastText(      # 2) FastText 학습(훈련)
    sentences,         # 학습 데이터(토큰화된 문장들)
    vector_size=50,    # 단어 벡터 차원 수
    window=3,          # 주변 문맥 범위(좌우 3개)
    min_count=1,       # 최소 등장 횟수(1 이상 단어만 사용)
    sg=1,              # 1=Skip-gram(중심→주변), 0=CBOW(주변→중심)
    min_n=2,           # 서브워드(문자 n-그램) 최소 길이
    max_n=5,           # 서브워드(문자 n-그램) 최대 길이
    epochs=50          # 전체 데이터 반복 학습 횟수
)

# 3) 단어 벡터 확인 : '자연어' 임베딩 벡터(50차원) 중 앞 10개 출력
print("자연어 벡터 일부:", model.wv["자연어"][:10])

# 4) 유사 단어(topn) : 코사인 유사도가 높은 단어 TOP3
print("자연어와 비슷한 단어:", model.wv.most_similar("자연어", topn=3))

# 5) 단어 간 유사도(코사인) : 두 단어 벡터의 코사인 유사도 스칼라 출력
print("similarity(자연어, 처리):", model.wv.similarity("자연어", "처리"))

# 6) OOV 예시: 학습에 없던 단어도 서브워드로 벡터 생성 가능
# "자연어처리" 미등장 단어라도 문자 n-그램으로 벡터 추정(앞 5개 출력)
print("OOV 단어 벡터 생성 가능?", model.wv["자연어처리"][:5])

자연어 벡터 일부: [ 0.00226604 -0.00067321 -0.00597979  0.00056262  0.00244565 -0.00171385
 -0.00238545 -0.00246523  0.00509697 -0.00276196]
자연어와 비슷한 단어: [('처리', 0.05201917141675949), ('파이썬', -0.022671055048704147), ('공부', -0.04659514129161835)]
similarity(자연어, 처리): 0.052019175
OOV 단어 벡터 생성 가능? [ 0.00084895 -0.00255903 -0.00200175  0.00446068 -0.00222416]


In [1]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

# 데이터 준비
corpus = ["자연어 처리는 재미있다", "Python은 강력하다"]
labels = [0, 1]

# 벡터화 및 분류
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
model = MultinomialNB()
model.fit(X, labels)

# 예측
print(model.predict(vectorizer.transform(["Python이 재미있다"])))

[0]


In [3]:
import torch 
import torch.nn as nn

class CNNClassifier(nn.Module):
    def __init__(self, vocab_size, embed_size, num_classes):
        super(CNNClassifier, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.conv = nn.Conv2d(1, 100, (3, embed_size))  # 3-gram 필터
        self.fc = nn.Linear(100, num_classes)

    def forward(self, x):
        x = self.embedding(x).unsqueeze(1)  # 채널 추가
        x = torch.relu(self.conv(x)).squeeze(3)
        x = torch.max(x, dim=2)[0]  # Max pooling
        x = self.fc(x)
        return x

In [4]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

# 데이터 준비
corpus = ["자연어 처리는 재미있다", "Python은 강력하다"]
labels = [[1, 0], [0, 1]]  # 다중 레이블

# 모델 정의
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
model = OneVsRestClassifier(LogisticRegression())
model.fit(X, labels)

# 예측
print(model.predict(vectorizer.transform(["Python이 재미있다"])))

[[1 0]]


In [1]:
from nltk.util import ngrams
from collections import Counter

# 샘플 텍스트
text = "자연어 처리는 재미있다."

# 2-gram 생성
tokens = text.split()
bigrams = list(ngrams(tokens, 2))
bigram_freq = Counter(bigrams)

print("2-gram:", bigrams)
print("2-gram 빈도:", bigram_freq)

2-gram: [('자연어', '처리는'), ('처리는', '재미있다.')]
2-gram 빈도: Counter({('자연어', '처리는'): 1, ('처리는', '재미있다.'): 1})


In [2]:
import math

# 예제 확률값
probs = [0.1, 0.2, 0.3, 0.4]
perplexity = math.pow(2, -sum(math.log2(p) for p in probs) / len(probs))
print("퍼플렉서티:", perplexity)

퍼플렉서티: 4.518010018049224


In [3]:
import torch
import torch.nn as nn

class NNLM(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super(NNLM, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_size)
        self.fc1 = nn.Linear(embed_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embed(x)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = NNLM(vocab_size=5000, embed_size=300, hidden_size=128)
print(model)

NNLM(
  (embed): Embedding(5000, 300)
  (fc1): Linear(in_features=300, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=5000, bias=True)
)


In [1]:
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

text = "Natural language processing is fascinating."
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tensor([[[-0.0247, -0.0657, -0.4309,  ..., -0.3628, -0.0277,  0.6678],
         [ 0.0786,  0.3412, -0.9526,  ..., -0.5415,  0.4421,  0.5844],
         [-0.4891,  0.3484,  0.0458,  ..., -0.7975, -0.2843,  0.2286],
         ...,
         [ 0.2925,  0.3500,  0.1258,  ..., -0.2860,  0.2030,  0.3638],
         [ 0.7109,  0.0265, -0.4232,  ...,  0.2195, -0.5607, -0.2824],
         [ 0.9015,  0.0171, -0.3039,  ...,  0.2657, -0.7258, -0.1695]]],
       grad_fn=<NativeLayerNormBackward0>)


In [2]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

input_text = "Artificial Intelligence is"
inputs = tokenizer(input_text, return_tensors="pt")
outputs = model.generate(inputs['input_ids'], max_length=20, num_return_sequences=1)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

c:\Users\playdata2\NLP\nlp_venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\playdata2\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Artificial Intelligence is a new field of research that has been gaining traction in recent years. It is
