# fastText

https://github.com/facebookresearch/fastText

**FastText**는 자연어 처리(NLP) 작업에서 사용되는 오픈소스 라이브러리로, 텍스트 분류 및 단어 임베딩을 위한 빠르고 효율적인 도구이다. 이는 Facebook AI Research 팀에서 개발했으며, 특히 대규모 텍스트 데이터에서도 높은 성능과 속도를 제공한다.

FastText는 2016년에 Facebook AI Research(FAIR) 팀에 의해 처음 공개되었다.  
처음 발표된 논문은 **"Enriching Word Vectors with Subword Information"** (2016)이며, 이후 오픈소스로 GitHub에 공개되어 많은 사용자들에게 활용되고 있다.  

FastText는 Word2Vec 이후 등장한 모델로, 특히 서브워드 정보 활용과 텍스트 분류에서 효율성을 강조하면서 주목받았다.

**주요 특징**
1. **단어 벡터 학습 (Word Embeddings)**  
   - FastText는 단어를 고정된 크기의 벡터로 변환하는 단어 임베딩 모델을 학습한다. 이는 단어의 의미를 벡터 공간에 매핑하여 유사한 단어가 가까운 벡터로 표현되도록 한다.
   - 기존의 Word2Vec과 유사하지만, FastText는 단어를 **서브워드(subword)** 단위로 처리한다.

2. **서브워드 기반 모델 (Subword-based Model)**  
   - 단어를 n-그램(예: 'apple' → ['app', 'ppl', 'ple'])으로 분해하여 학습하기 때문에, **희귀 단어**나 **철자 오류**에도 강건하다.
   - 이는 단어 외에도 철자 패턴과 같은 더 세밀한 정보를 학습하는 데 유용하다.

3. **텍스트 분류 (Text Classification)**  
   - FastText는 문서나 문장을 빠르고 정확하게 분류하는 데 최적화되어 있다.
   - 학습 과정이 빠르고, 모델의 크기가 작으며, 정확도도 뛰어나다.

4. **효율적인 구현**  
   - FastText는 CPU 기반으로도 높은 성능을 내도록 설계되었으며, 대규모 데이터셋에서도 빠르게 작동한다.

**FastText의 작동 원리**
1. **단어 표현**  
   - 단어를 n-그램 서브워드로 나눈 후, 각 서브워드에 대해 벡터를 학습한다.
   - 예를 들어, "cat"이라는 단어는 'c', 'ca', 'cat'과 같은 다양한 조합으로 분해된다.
   - 결과적으로 단어 벡터는 각 서브워드 벡터의 합으로 표현된다.

2. **모델 구조**  
   - FastText는 Skip-gram 모델이나 CBOW 모델을 기반으로 동작한다.
   - 단, 기존 모델과 달리 단어 자체가 아닌 서브워드를 사용하여 학습한다.

**FastText의 장점**
1. **희귀 단어 처리 능력**  
   - 서브워드 기반 접근 방식 덕분에 희귀 단어 또는 새로운 단어에 대해 더 좋은 일반화 성능을 발휘한다.
2. **빠른 학습 속도**  
   - 단순한 모델 구조와 최적화된 구현으로 매우 빠르게 학습할 수 있다.
3. **다양한 언어 지원**  
   - 다양한 언어에서 동작하며, 특히 굴절어(inflected languages)와 같은 복잡한 언어에서도 효과적이다.

**활용 사례**
1. **단어 임베딩**  
   - 단어 간 유사도 계산, 문장 표현 학습.
2. **텍스트 분류**  
   - 스팸 필터링, 감정 분석, 뉴스 분류.
3. **다언어 지원**  
   - 다국어 데이터셋에서 빠른 응답 성능 제공.

In [50]:
!gdown https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ

Downloading...
From (original): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ
From (redirected): https://drive.google.com/uc?id=1vyZuUgbejAnx8xicQnQ1HgtW6avN8ZRQ&confirm=t&uuid=9a75a88c-65b5-40dc-b71e-275f00af0816
To: c:\Users\playdata2\NLP\03_text_vectorization\ted_en-20160408.xml

  0%|          | 0.00/74.5M [00:00<?, ?B/s]
  1%|          | 524k/74.5M [00:00<00:22, 3.24MB/s]
  5%|▍         | 3.67M/74.5M [00:00<00:04, 16.0MB/s]
 15%|█▌        | 11.5M/74.5M [00:00<00:01, 38.5MB/s]
 30%|██▉       | 22.0M/74.5M [00:00<00:00, 57.9MB/s]
 38%|███▊      | 28.3M/74.5M [00:00<00:00, 54.2MB/s]
 56%|█████▋    | 41.9M/74.5M [00:00<00:00, 77.0MB/s]
 69%|██████▉   | 51.4M/74.5M [00:00<00:00, 80.7MB/s]
 82%|████████▏ | 60.8M/74.5M [00:00<00:00, 83.6MB/s]
 94%|█████████▍| 70.3M/74.5M [00:01<00:00, 85.6MB/s]
100%|██████████| 74.5M/74.5M [00:01<00:00, 67.7MB/s]


In [51]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\playdata2\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\playdata2\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\playdata2\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [52]:
from lxml import etree

xml = open('ted_en-20160408.xml', 'r', encoding='utf-8')
tree = etree.parse(xml)

content = tree.xpath('//content/text()')
print(len(content))

corpus = '\n'.join(content)

2085


In [53]:
import re
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

corpus = re.sub(r'\([^)]*\)', '', corpus)
corpus = re.sub(r'[^a-z0-9\s.,!?]+', '', corpus, flags=re.IGNORECASE)
corpus = corpus.lower()

en_stopwords = stopwords.words('english')

sentences = sent_tokenize(corpus)
normalized_sentences = []

for sent in sentences:
    tokens = word_tokenize(sent)
    normalized_tokens = [token for token in tokens if token not in en_stopwords]
    normalized_sentences.append(normalized_tokens)

print(f'총 문장 수: {len(normalized_sentences)}')

총 문장 수: 271088


In [54]:
%%time
from gensim.models.fasttext import FastText

model = FastText(
    normalized_sentences,
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    sg=1
)

CPU times: total: 2min 20s
Wall time: 40.7 s


In [55]:
model.wv.vectors.shape

(22174, 100)

In [56]:
print(model.wv.most_similar('man'))
print(model.wv.similarity('man', 'woman'))

[('woman', 0.8367373943328857), ('batman', 0.8045951128005981), ('hoffman', 0.7771780490875244), ('manju', 0.7457199692726135), ('shaman', 0.7435176968574524), ('lehman', 0.7434993982315063), ('stuntman', 0.7393485307693481), ('fireman', 0.7360060811042786), ('womans', 0.7337956428527832), ('roman', 0.7330761551856995)]
0.8367375


In [57]:
print(model.wv.get_index('apple'))
print(model.wv.vectors[1620][:5])
print(model.wv.get_vector('apple')[:5])

# print(model.wv.get_index('ultramicrosafe'))
print(model.wv.get_vector('ultramicrosafe')[:5])

1618
[-0.37277368  0.51618016 -0.02200385 -0.12721004  0.28190157]
[ 0.15163383  0.41888687  0.3847039   0.04393172 -0.13425872]
[-0.0512173   0.29458728  0.04025728 -0.00829971  0.13634264]


In [58]:
import numpy as np

word = 'apple'
word_vec = model.wv.get_vector(word)
print(word_vec[:5])

word_idx = model.wv.get_index(word)
print(word_idx)

base_vec = model.wv.vectors_vocab[word_idx]
print(base_vec[:5])

subword_index = model.wv.buckets_word[word_idx]
subword_vecs = model.wv.vectors_ngrams[subword_index]
print(subword_vecs.shape)
print(subword_vecs[:, :5])

calc_vec = np.vstack((base_vec, subword_vecs)).mean(axis=1)
print(calc_vec[:5])

[ 0.15163383  0.41888687  0.3847039   0.04393172 -0.13425872]
1618
[ 0.11495961 -0.21971792  0.2689501  -0.01952842 -0.3028386 ]
(14, 100)
[[-0.16724774  0.97137725  0.8107704   0.8857529  -0.31837773]
 [ 0.245008    1.1562262   0.09135085  0.24461041 -0.1813637 ]
 [ 0.7080801   0.4084761   0.43433204 -0.6480607   0.00255487]
 [ 0.25801772 -0.07117968  0.4452768   0.17176986 -0.36943132]
 [-0.95223737  1.0397657  -0.36011142  0.40101796 -0.19523904]
 [ 0.5437011   0.42868456  0.26161328 -0.5295802   0.07517245]
 [ 0.08857369 -0.20937325  0.23413606 -0.09235668 -0.10722909]
 [-0.00874837 -0.15003262  0.158104    0.01883652 -0.2023966 ]
 [ 0.1789893   0.5286724   0.23723947 -0.58313555  0.41786277]
 [ 0.12156762 -0.13472232  0.37875107  0.03844592 -0.10049849]
 [-0.12667419 -0.09585921  0.10423774  0.13744581 -0.14965782]
 [-0.30079815  0.67507356 -0.01424276  0.24669003  0.58190805]
 [ 0.93163186  0.91363204  0.5734826   0.16287553  0.05016893]
 [ 0.63968426  1.0422803   2.1466682   0.2

In [60]:
sent_vec = model.wv.get_sentence_vector("I lone apple very much~")
sent_vec.shape

(100,)

In [63]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

sentences = [
    'i love apple',
    'apple is good',
    'i hate banana',
    'banana is yellow'
]

sent_vecs = np.array([model.wv.get_sentence_vector(sent) for sent in sentences])
print(sent_vecs.shape)

sent_cos_sim = cosine_similarity(sent_vecs)

pd.DataFrame(
    sent_cos_sim,
    columns=sentences,
    index=sentences
)

(4, 100)


,i love apple,apple is good,i hate banana,banana is yellow
i love apple,1.000000,0.921975,0.750280,0.897267
apple is good,0.921975,1.000000,0.692391,0.850211
i hate banana,0.750280,0.692391,1.000000,0.895498
banana is yellow,0.897267,0.850211,0.895498,1.000000


In [64]:
model.save('ted_en_fasttext.model')

In [65]:
model2 = FastText.load('ted_en_fasttext.model')
model2

In [66]:
model2.wv.most_similar('woman')

[('womans', 0.8499589562416077),
 ('man', 0.8367374539375305),
 ('womanhood', 0.8181167840957642),
 ('lehman', 0.795647144317627),
 ('hoffman', 0.791959822177887),
 ('fireman', 0.7701817154884338),
 ('batman', 0.7665940523147583),
 ('stuntman', 0.7509971261024475),
 ('stroman', 0.7485163807868958),
 ('roman', 0.7318140268325806)]