In [2]:
import math

p = [1, 2]
q = [4, 6]

distance = math.dist(p, q)
print(distance)   # 출력: 5.0

5.0


In [3]:
p = [1, 2]
q = [4, 6]

manhattan = sum(abs(pi - qi) for pi, qi in zip(p, q))
print(manhattan)   # 출력: 7

7


In [4]:
import numpy as np

p = np.array([1, 2])
q = np.array([2, 3])

cos_sim = np.dot(p, q) / (np.linalg.norm(p) * np.linalg.norm(q))
print(round(cos_sim, 3))   # 출력: 0.983

0.992


In [5]:
import numpy as np
from scipy.spatial.distance import mahalanobis

# 샘플 데이터(공분산 계산용)
data = np.array([
    [1, 2],
    [2, 2],
    [3, 4]
])

p = np.array([1, 2])
q = np.array([3, 4])

cov = np.cov(data.T)               # 공분산 행렬
inv_cov = np.linalg.inv(cov)       # 공분산 역행렬

dist = mahalanobis(p, q, inv_cov)
print(round(dist, 3))  # 예: 2.0

2.0


In [6]:
import numpy as np

theta = np.array([0.5, 1.0])   # 가중치
x = np.array([1, 2])           # 입력 데이터

z = theta @ x                  # 선형 조합 (θ^T x)
sigmoid = 1 / (1 + np.exp(-z)) # 시그모이드 함수

print(round(sigmoid, 3))       # 예: 0.924

0.924


In [7]:
import numpy as np

# 간단한 데이터 (x: 특성, y: 레이블)
x = np.array([0.2, 0.8, 1.5])                     # 입력 특성 값들
y = np.array([0, 1, 1])                           # 실제 정답 레이블 (0/1)

theta = 1.0                                       # 임의의 가중치값 θ
z = theta * x                                     # 선형 결합 z = θx
h = 1 / (1 + np.exp(-z))                          # 시그모이드 함수 → 예측 확률 h(x)

# Log Loss 계산
log_loss = -np.mean(y*np.log(h) + (1-y)*np.log(1-h))   # 로지스틱 회귀의 비용 함수(Log Loss)
print(round(log_loss, 3))              # 예: 0.391       # 계산된 손실값 출력

# 예측 (threshold=0.5)
pred = (h >= 0.5).astype(int)                      # 0.5 이상이면 1, 아니면 0으로 분류
print(pred)                             # 예: [0 1 1]    # 최종 예측 결과

0.457
[1 1 1]


In [8]:
import numpy as np

# 클래스 3개에 대한 점수(θᵀx 값)
scores = np.array([2.0, 1.0, 0.1])

# 소프트맥스 함수
exp_scores = np.exp(scores)
softmax = exp_scores / np.sum(exp_scores)

print(np.round(softmax, 3))   # 예: [0.659 0.242 0.099]

[0.659 0.242 0.099]


In [9]:
import numpy as np

# 입력 벡터
x = np.array([1.2, 0.5])

# 각 레이블별 가중치 (3개의 레이블: 액션, 코미디, 드라마)
theta = np.array([
    [1.0, -0.5],   # 액션
    [-0.3, 1.2],   # 코미디
    [0.8, 0.8]     # 드라마
])

# 레이블별 선형 조합 + 시그모이드
z = theta @ x
sigmoid = 1 / (1 + np.exp(-z))

print(np.round(sigmoid, 3))   # 예: [0.777 0.622 0.845]

[0.721 0.56  0.796]


In [10]:
import numpy as np

x = np.array([1.0, 0.5])   # 입력 특징

# 출력 1: 질병 유무 (이진 분류 → 시그모이드)
theta_disease = np.array([1.2, -0.8])
z1 = theta_disease @ x
disease_prob = 1 / (1 + np.exp(-z1))

# 출력 2: 중증도 (4개 클래스 → 소프트맥스)
theta_severity = np.array([
    [0.5, 1.0],
    [1.0, -0.2],
    [-0.5, 0.7],
    [0.2, 0.1]
])
z2 = theta_severity @ x
exp_scores = np.exp(z2)
severity_prob = exp_scores / np.sum(exp_scores)

print("질병 확률:", round(disease_prob, 3))
print("중증도 확률:", np.round(severity_prob, 3))

질병 확률: 0.69
중증도 확률: [0.371 0.336 0.118 0.175]


In [11]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0])   # 실제값
y_pred = np.array([1, 0, 0, 1, 0])   # 예측값

TP = np.sum((y_true == 1) & (y_pred == 1))
TN = np.sum((y_true == 0) & (y_pred == 0))
FP = np.sum((y_true == 0) & (y_pred == 1))
FN = np.sum((y_true == 1) & (y_pred == 0))

accuracy = (TP + TN) / len(y_true)
print("Accuracy:", round(accuracy, 3))   # 예: 0.8

Accuracy: 0.8


In [12]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0])
y_pred = np.array([1, 1, 0, 1, 0])

# Confusion Matrix 요소 계산
TP = np.sum((y_true == 1) & (y_pred == 1))
TN = np.sum((y_true == 0) & (y_pred == 0))
FP = np.sum((y_true == 0) & (y_pred == 1))
FN = np.sum((y_true == 1) & (y_pred == 0))

print(f"TP={TP}, FP={FP}, FN={FN}, TN={TN}")

TP=2, FP=1, FN=1, TN=1


In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# 데이터 로드 및 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42)

# 모델 학습
model = LogisticRegression()
model.fit(X_train, y_train)

# 예측 확률 확인
proba = model.predict_proba(X_test)
print(proba)

[[4.09968912e-03 8.12343895e-01 1.83556416e-01]
 [9.41955393e-01 5.80440269e-02 5.80204086e-07]
 [1.58411647e-08 2.09129455e-03 9.97908690e-01]
 [6.82490784e-03 7.73251455e-01 2.19923637e-01]
 [1.59400726e-03 7.51206041e-01 2.47199952e-01]
 [9.50040934e-01 4.99586069e-02 4.58820360e-07]
 [7.78025723e-02 9.04144967e-01 1.80524606e-02]
 [1.79836286e-04 1.47357775e-01 8.52462389e-01]
 [2.42255905e-03 7.80452458e-01 2.17124982e-01]
 [2.89983399e-02 9.40818571e-01 3.01830888e-02]
 [4.73570875e-04 2.25282362e-01 7.74244068e-01]
 [9.62693674e-01 3.73061419e-02 1.84138480e-07]
 [9.69162366e-01 3.08375374e-02 9.66511405e-08]
 [9.56006722e-01 4.39930121e-02 2.65383349e-07]
 [9.76521680e-01 2.34781303e-02 1.89458968e-07]
 [4.76687522e-03 6.63398836e-01 3.31834289e-01]
 [9.67228295e-06 2.67217786e-02 9.73268549e-01]
 [2.76880806e-02 9.45164474e-01 2.71474455e-02]
 [8.70365053e-03 8.20159571e-01 1.71136778e-01]
 [1.93849853e-05 4.14384101e-02 9.58542205e-01]
 [9.58706136e-01 4.12934111e-02 4.533375